### ISSUE TITLE
"Accessing data with MySQL" guide does not work

### ISSUE THREAD

**Issue by james-bates-omio** [spring-guides/gs-accessing-data-mysql#26]
Following the steps in https://spring.io/guides/gs/accessing-data-mysql/ to the letter, the application fails to start with the following error:

```
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:94) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	... 33 common frames omitted
```

Presumably, some configuration is missing. Or Spring boot is broken.

**Comment by Maokaitou** [comment]
try add 'spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect' to application.properties

**Comment by dsyer** [comment]
You don’t need to do that, though, if the application can connect to the database (it will figure out the dialect).

**Comment by jimsar** [comment]
@dsyer Hi !
I used the "complete" from this guide in Android Studio. But when i close the project and run it again, I face the following error:

APPLICATION FAILED TO START

Description:
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class
Action:
Consider the following:
If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

What is wrong with this project?

**Comment by dsyer** [comment]
So maybe the database isn’t running?

**Comment by jimsar** [comment]
Mysql db is running. Also when I firstly open the project in Android Studio, the connection is fine. The error appears when I close the project and run it again. I think something is going wrong after some synchronizing by Android Studio, or something about Maven and Gradle.

**Comment by dsyer** [comment]
I don't know how Android Studio could be making a difference. How about if you run the app from the command line (e.g. `./mvnw spring-boot:run`)? Does it work there? The error is telling us you can't connect to the database. Is it running on localhost? Did you change anything about the database when you restarted the app? Some more logs might shed some light.

**Comment by jimsar** [comment]
I think the error is telling us "url" is not able to be configured. But no changes before restarting the app. Its happening every time I am deleting the project, then downloading again from spring.io and running, and restarting Android Studio and running again.  Maybe something about Maven and Gradle at the same time in this project?

**Comment by dsyer** [comment]
Let's leave Android Studio out of it for now. Can you run the project (with either Maven or Gradle) from the command line?

**Comment by jimsar** [comment]
Thank you for the response.
Yes, it's up right now. I did it with Maven.
What do you think is the matter with AS?

**Comment by dsyer** [comment]
> What do you think is the matter with AS?

No idea. Ask in an Android forum?

**Comment by Nooaah** [comment]
> 

This works for me 👌
